version: '2.1'

jobs:
  build:
    docker:
      - image: maven:3.8.6-openjdk-17
    steps:
      - checkout
      - run:
          name: Set up Maven cache
          command: |
            mkdir -p ~/.m2
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build the project
          command: mvn clean install
      - save_cache:
          key: maven-cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  test:
    docker:
      - image: maven:3.8.6-openjdk-17
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn test

  deploy:
    docker:
      - image: maven:3.8.6-openjdk-17
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Package application
          command: mvn package
      - run:
          name: Deploy application
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              mvn deploy
            fi

workflows:
  version: '2'
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main